### ISSUE TITLE
Extended Command Line LFN issue

### ISSUE THREAD

**Issue by shidel** [FDOS/freecom#97] opened 2024-05-25 14:31 UTC
As mentioned briefly in issue https://github.com/FDOS/freecom/issues/95, there is a separate issue with the extended command line.

I'm not sure if this technically a bug. However, it makes it excessively cumbersome for a program to correctly parse an extended command line that is passed through the `CMDLINE` environment variable. 

The issue is Long File Names. So, first I will demonstrate what happens. Ignore the errors regarding the missing carriage return, that should be fixed in pull request https://github.com/FDOS/freecom/pull/96

So, I created a LFN directory, changed into it and ran the test program with a very long set of parameters.

![Screen Shot 2024-05-25 at 9 45 43 AM](https://github.com/FDOS/freecom/assets/10198034/0f36c4fb-33a2-451f-a2b4-c5aff080017c)

Looks good. So, I move up one directory, used the short name for LFN directory to execute the test again.

![Screen Shot 2024-05-25 at 9 48 07 AM](https://github.com/FDOS/freecom/assets/10198034/8d26cad8-6fb4-45ef-b691-06be46c28a48)

Looks good. So, I then used the LFN version of the directory and ran the test again. 

![Screen Shot 2024-05-25 at 9 46 46 AM](https://github.com/FDOS/freecom/assets/10198034/48af75a9-90ed-433c-a844-3ea140d7e03e)

Um. Not so good. Where did the quotes go? Look at all of those spaces. 

This makes it more difficult for the program to determine the first parameter passed on the command line.

For example: Was the program extension included? What if program was renamed? 

Although I did not rename the binary to use an LFN, I would assume it would exhibit the same issue. 

I can see how I could reliably find the start of the first parameter after the program (even from a com file). It is not going to be fun to process in the program and most programs probably won't bother.  I think it would be more practical and reliable to change this behavior.

There are three potential solutions to the issue.

First, simply keep the quotes. This would be the easiest. But, I am not sure how well programs that support the CMDLINE variable will handle having them present. 

Second, always send the short name in the CMDLINE variable. This should be very reliable. However, it would require running that portion of the string through the [GET SHORT NAME](https://fd.lod.bz/rbil/interrup/dos_kernel/217160cl01.html) function provided by the LFN driver. As long as the driver is functioning properly, this may be the best solution and should not have any adverse side effects. 

Third, just strip that out and put a dummy name there. It is doubtful any programs are relying on the included executable name, they will be expecting something there. Stripping out the information passed regarding the executable and replacing it with something like `PROGRAM  `, should be good. But, would need testing.

**Comment by ecm-pushbx** [comment] 2024-05-25 20:55
I used your tstcmdln.com and on MSW 98 SE (with its command.com and with Windows loaded to provide LFNs) it does pass along the double quote marks of the command when I run the program from a directory with a long name.

**Comment by shidel** [comment] 2024-05-25 21:00
@ecm-pushbx, thanks. 
That answers how it should be solved. 
Quotes should be present.

**Comment by ecm-pushbx** [comment] 2024-05-25 21:00
Same if the program filename is also long. Interestingly enough I *can* run a long named executable but the short name is passed to interrupt 21h function 4Bh. I can't put a breakpoint on function 71h however, as in the debugger won't gain control. This is likely because the MSWindows handler hooks the interrupt in its PM handler so the function 71h is never passed to the DOS.

**Comment by shidel** [comment] 2024-06-05 15:34
Another concern... Be sure to check how microsoft will handle a file or directory that includes a quote in the name. Will it be escaped, double quoted or something else.

**Comment by ecm-pushbx** [comment] 2024-06-05 15:46
I don't think doublequote marks are allowed in filenames.

**Comment by shidel** [comment] 2024-06-05 15:54
> I don't think doublequote marks are allowed in filenames.

I now you can have them on Mac, Linux, BSD, etc. 

I've been away from Windows for a very long time. I honestly do not recall if it is doable. It will require some checking. It may not be possible in short names. It may not be possible for a user in long file names. But, it may be possible for a program to do it. I really don't know.

**Comment by ecm-pushbx** [comment] 2024-06-05 16:26
Refer to the answer and comments in https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names/31976060#31976060

**Comment by PerditionC** [comment] 2024-12-24 19:59
I believe the issue is fixed by PR 104, please reopen or open a new issue if there are aspects of this issue that are still unresolved.

**Closed by PerditionC** 2024-12-24 19:59 UTC
Labels: bug
